spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
#              memory: 256Mi
            limits:
              cpu: "1.0"
#              memory: 256Mi
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: amq63-broker-amq-tcp
          - name: ACTIVEMQ_BROKER_USERNAME
            value: amq
          - name: ACTIVEMQ_BROKER_PASSWORD
            value: amq@ocp
          - name: ACTIVEMQ_POOL_MAX_CONNECTIONS
            value: 8
          - name: ACTIVEMQ_CONCURRENT_CONSUMERS
            value: 10
          - name: ACTIVEMQ_INPUT_DESTINATION1
            value: queue:TRANSACTED.TEST
          - name: ACTIVEMQ_INPUT_DESTINATION2
            value: queue:TRANSACTED.TEST2
          - name: ACTIVEMQ_INPUT_DESTINATION3
            value: queue:TRANSACTED.TEST3
          - name: ACTIVEMQ_INPUT_DESTINATION4
            value: queue:TRANSACTED.TEST4
